### ISSUE TITLE
Project doesn't work

### ISSUE THREAD

**Issue by Pong50887** [Karczel/ku-polls#13]
It seems like there is some error in your code, I Can't open the project.

**Comment by Karczel** [comment]
Have you tried cloning the project at the outmost ku-polls directory of the project and:
```python3 manage.py migrate```
```python3 manage.py loaddata data/polls-v1.json```
```python3 manage.py rumserver```
Use google chrome as you might be block on firewall of Safari
and type:
```localhost:8000/polls/```
in the search bar?

**Comment by Karczel** [comment]
contacted directly and resolved issue
