### ISSUE TITLE
requirements.txt error

### ISSUE THREAD

**Issue by oaoak** [Karczel/ku-polls#52]
It's better to provides a range for requirements rather than 'Django==5.1.1'. In this case, I got an error 'Django==5.1.1' not found which I could not continue inspecting your repository. 'Django >= 4.2, <5.0' something like this should be better.

**Comment by Karczel** [comment]
I have changed that, thank you

**Comment by Karczel** [comment]
Please close this issue once it works on your side

**Comment by oaoak** [comment]
working now
